# Generated by Django 3.0.3 on 2020-02-25 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight_recorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weight',
            options={'ordering': ('weight_date',), 'verbose_name': 'Peso'},
        ),
    ]
